# Generated by Django 2.2.16 on 2022-12-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': ('Название',), 'verbose_name_plural': 'Названия'},
        ),
    ]
