# Generated by Django 3.2.16 on 2022-12-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221204_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genreandtitle',
            options={'verbose_name': ('Жанр и название',), 'verbose_name_plural': 'Жанры и названия'},
        ),
    ]
