# Generated by Django 2.2.16 on 2022-12-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221209_2359'),
        ('reviews', '0004_auto_20221209_1718'),
    ]

    operations = [
    ]
